# Generated by Django 4.2.7 on 2024-01-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_remove_checkoutdb_town_alter_checkoutdb_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdb',
            name='Town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
