# Generated by Django 4.2.7 on 2024-01-03 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0009_cartdb_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='ProductImage',
        ),
    ]
